#!/bin/bash
#  script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line using while loop and if statement
i=2
while (( i>11))
do
	echo "Best School"
	if (( i == 9 ))
	then 
		echo "Best School"
		echo "Hi"
	fi
	(( i++ ))
done
