#!/usr/bin/env bash
# script that displays: The content of the current directory, In a list format, Where only the part of the name after the first dash is displayed
for file in *; do
    if [[ -f "$file" && ! -L "$file" ]]; then
        echo "${file#*-}"
    fi
done
