#!/usr/bin/env bash
# Process and PID file

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -vf /var/run/myscript.pid; exit' SIGQUIT
done
